name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  task:
    description: 'input description here'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
